### ISSUE TITLE
Connector user for Self Description document on root context

### ISSUE THREAD

**Issue by IgorBalog-Eng** [Engineering-Research-and-Development/true-connector-execution_core_container#157]
Currently ADMIN user, which is used for API operations is used to fetch Self Description document on root context.
This should be changed, and Connector user should be used instead.

SecurityConfig
.antMatchers("/").hasRole("CONNECTOR")
instead
.antMatchers("/").hasRole("ADMIN")

Update documentation/postman collections/GHA accordingly.

**Comment by davidjovanovic** [comment]
In the meantime the requirements changed to dropping authorization for SD on root. Which was done here #193
