### ISSUE TITLE
Error is printed in log when requesting self description

### ISSUE THREAD

**Issue by IgorBalog-Eng** [Engineering-Research-and-Development/true-connector-execution_core_container#192]
When running dockerized environment, and requesting SD - https://localhost:8090, following lines are printed in log, but SD is returned.
Investigate how to solve this error (might be related with another port configuration, TLS vs nonTLS)

java.lang.NullPointerException
ecc-provider         |  at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.getSslSupport(NioEndpoint.java:1392)
ecc-provider         |  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
ecc-provider         |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1593)
ecc-provider         |  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
ecc-provider         |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ecc-provider         |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ecc-provider         |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ecc-provider         |  at java.base/java.lang.Thread.run(Unknown Source)

**Comment by davidjovanovic** [comment]
This was a bug in some versions of Tomcat including 9.0.24. An update to the newest 9.0.76 fixed it.
